import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { getChatGPTUser } from "../../../chatgpt-auth";
import { getDb } from "../../../../db/index";
import { importRuns,jobs,profiles } from "../../../../db/schema";
import { fingerprint,validJob,type ImportedJob } from "../../../../lib/jobs";
import { parseCsvJobs } from "../../../../lib/csv-jobs";
export const dynamic="force-dynamic";
const ADMINS=new Set(["contato@amrsolution.com.br","alexsandro.ramos@gmail.com","prof.andreiamr@gmail.com"]);
async function payload(request:Request){const type=request.headers.get("content-type")??"";if(type.includes("text/csv")){const text=await request.text();if(text.length>2_000_000)throw new Error("Arquivo CSV excede 2 MB");return parseCsvJobs(text)}const value=await request.json();return(Array.isArray(value)?value:value.jobs) as unknown[]}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return NextResponse.json({error:"Autenticação necessária"},{status:401});const profile=(await getDb().select({role:profiles.role}).from(profiles).where(eq(profiles.userId,user.userId)).limit(1))[0];if(profile?.role!=="admin"&&!ADMINS.has(user.email.toLowerCase()))return NextResponse.json({error:"Acesso de administrador necessário"},{status:403});let items:unknown[];try{items=await payload(request)}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Formato inválido"},{status:400})}if(!Array.isArray(items)||!items.length)return NextResponse.json({error:"Envie vagas em JSON ou CSV com cabeçalhos válidos"},{status:400});if(items.length>2000)return NextResponse.json({error:"O limite é de 2.000 vagas por importação"},{status:400});const runId=crypto.randomUUID(),db=getDb(),startedAt=new Date();await db.insert(importRuns).values({id:runId,source:request.headers.get("content-type")?.includes("text/csv")?"csv":"manual",status:"running",received:items.length,actorUserId:user.userId,startedAt});let inserted=0,updated=0,errors=0;for(const item of items){if(!validJob(item)){errors++;continue}const job=item as ImportedJob,fp=fingerprint(job),now=new Date(),existing=(await db.select({id:jobs.id}).from(jobs).where(eq(jobs.fingerprint,fp)).limit(1))[0],values={id:existing?.id??crypto.randomUUID(),fingerprint:fp,sourceId:job.sourceId??null,externalId:job.externalId??null,company:job.company.trim(),title:job.title.trim(),seniority:job.seniority??null,workMode:job.workMode??null,location:job.location??null,stack:JSON.stringify(job.stack??[]),publishedAt:job.publishedAt?new Date(job.publishedAt):null,url:job.url,description:job.description??"",firstSeenAt:now,lastSeenAt:now,status:"active" as const,createdAt:now,updatedAt:now};await db.insert(jobs).values(values).onConflictDoUpdate({target:jobs.fingerprint,set:{company:values.company,title:values.title,seniority:values.seniority,workMode:values.workMode,location:values.location,stack:values.stack,publishedAt:values.publishedAt,url:values.url,description:values.description,lastSeenAt:now,status:"active",updatedAt:now}});existing?updated++:inserted++}await db.update(importRuns).set({status:"completed",inserted,updated,errors,duplicates:0,finishedAt:new Date()}).where(eq(importRuns.id,runId));return NextResponse.json({ok:true,runId,received:items.length,inserted,updated,errors})}
