import { and,desc,eq } from "drizzle-orm";import { NextResponse } from "next/server";import { getChatGPTUser } from "../../../chatgpt-auth";import { getDb } from "../../../../db/index";import { jobSources,profiles } from "../../../../db/schema";import { collect, isPullProvider } from "../../../../lib/connectors";import { parseCareerSource } from "../../../../lib/career-source";import { CURATED_SOURCES } from "../../../../lib/curated-sources";
async function admin(){const u=await getChatGPTUser();if(!u)return null;const p=(await getDb().select({role:profiles.role}).from(profiles).where(eq(profiles.userId,u.userId)).limit(1))[0];return p?.role==="admin"||new Set(["contato@amrsolution.com.br","alexsandro.ramos@gmail.com","prof.andreiamr@gmail.com"]).has(u.email.toLowerCase())?u:null}
export const dynamic="force-dynamic";
export async function GET(){if(!await admin())return NextResponse.json({error:"Acesso de administrador necessário"},{status:403});const rows=await getDb().select().from(jobSources).orderBy(desc(jobSources.createdAt));return NextResponse.json({sources:rows.map(({externalRef,...source})=>({...source,externalRef:source.collectionMode==="pull"?externalRef:null,canCollect:source.collectionMode==="pull"&&isPullProvider(source.provider),catalogId:CURATED_SOURCES.find(item=>item.provider===source.provider&&item.externalRef===externalRef)?.id}))})}
export async function POST(request:Request){if(!await admin())return NextResponse.json({error:"Acesso de administrador necessário"},{status:403});const b=await request.json() as {name?:string;provider?:string;careerUrl?:string;externalRef?:string;test?:boolean};let parsed;try{parsed=b.careerUrl?parseCareerSource(b.careerUrl,b.provider):null}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Link inválido"},{status:400})}const provider=parsed?.provider??b.provider,externalRef=parsed?.externalRef??b.externalRef?.trim(),name=b.name?.trim()||parsed?.suggestedName;if(!name||!externalRef||!isPullProvider(provider??""))return NextResponse.json({error:"Informe uma empresa e um link público Greenhouse, Lever ou Ashby."},{status:400});let available:number|undefined;try{if(b.test)available=(await collect(provider,externalRef,name)).length}catch(error){return NextResponse.json({error:error instanceof Error?`Não localizamos uma página pública nesse endereço: ${error.message}`:"Não foi possível testar esta fonte"},{status:400})}const source={id:crypto.randomUUID(),name,provider,collectionMode:"pull" as const,externalRef,enabled:true,lastRunAt:null,createdAt:new Date()};await getDb().insert(jobSources).values(source);return NextResponse.json({ok:true,source,available})}

export async function PUT(){if(!await admin())return NextResponse.json({error:"Acesso de administrador necessário"},{status:403});const db=getDb();let added=0,reactivated=0;for(const item of CURATED_SOURCES){const existing=(await db.select().from(jobSources).where(and(eq(jobSources.provider,item.provider),eq(jobSources.externalRef,item.externalRef))).limit(1))[0];if(!existing){await db.insert(jobSources).values({id:crypto.randomUUID(),name:item.name,provider:item.provider,collectionMode:"pull",externalRef:item.externalRef,enabled:true,lastRunAt:null,createdAt:new Date()});added++}else if(!existing.enabled){await db.update(jobSources).set({enabled:true}).where(eq(jobSources.id,existing.id));reactivated++}}return NextResponse.json({ok:true,added,reactivated,total:CURATED_SOURCES.length})}

export async function PATCH(request:Request){if(!await admin())return NextResponse.json({error:"Acesso de administrador necessário"},{status:403});const b=await request.json() as {id?:string;enabled?:boolean};if(!b.id||typeof b.enabled!=="boolean")return NextResponse.json({error:"Fonte e estado são obrigatórios"},{status:400});await getDb().update(jobSources).set({enabled:b.enabled}).where(eq(jobSources.id,b.id));return NextResponse.json({ok:true})}
