"use client";

import { useEffect,useState } from "react";

type Settings={collectionEnabled:boolean;emailImportEnabled:boolean;enrichmentEnabled:boolean;scheduledTriageEnabled:boolean;scheduledTriageBatchSize:number;scheduledTriageDraftQueueEnabled:boolean;scheduledTriageAutoCreateEnabled:boolean;defaultPeriod:string;defaultMinScore:number;staleAfterDays:number;retentionDays:number};
type JobSummary={total:number;active:number;closed:number};
type JobPreview={before:string;selected:number};
const initial:Settings={collectionEnabled:true,emailImportEnabled:true,enrichmentEnabled:true,scheduledTriageEnabled:false,scheduledTriageBatchSize:100,scheduledTriageDraftQueueEnabled:true,scheduledTriageAutoCreateEnabled:true,defaultPeriod:"24",defaultMinScore:70,staleAfterDays:7,retentionDays:180};
const CONFIRMATION="EXCLUIR TODAS AS VAGAS";
const defaultCutoffDate=()=>`${new Date().toISOString().slice(0,7)}-01`;

export default function AdminSettings({isOwner}:{isOwner:boolean}){
 const[s,setS]=useState(initial),[status,setStatus]=useState("Carregando parâmetros…"),[jobs,setJobs]=useState<JobSummary|null>(null),[confirmation,setConfirmation]=useState(""),[cleaning,setCleaning]=useState(false),[cutoffDate,setCutoffDate]=useState(defaultCutoffDate),[cutoffConfirmation,setCutoffConfirmation]=useState(""),[preview,setPreview]=useState<JobPreview|null>(null),[previewLoading,setPreviewLoading]=useState(false),[cleaningBefore,setCleaningBefore]=useState(false);
 useEffect(()=>{let cancelled=false;Promise.all([fetch("/api/admin/settings"),fetch("/api/admin/jobs")]).then(async([settingsResponse,jobsResponse])=>({settingsResponse,jobsResponse,settings:await settingsResponse.json(),summary:await jobsResponse.json()})).then(({settingsResponse,jobsResponse,settings,summary})=>{if(cancelled)return;if(!settingsResponse.ok||!jobsResponse.ok)throw new Error();setS(settings.settings);setJobs(summary);setStatus("")}).catch(()=>{if(!cancelled)setStatus("Não foi possível carregar os parâmetros.")});return()=>{cancelled=true}},[]);
 useEffect(()=>{let cancelled=false;if(!cutoffDate){setPreview(null);return}setPreviewLoading(true);fetch(`/api/admin/jobs?before=${encodeURIComponent(cutoffDate)}`).then(async response=>({ok:response.ok,data:await response.json()})).then(({ok,data})=>{if(!cancelled){setPreview(ok?data:null);if(!ok)setStatus(data.error??"Não foi possível consultar as vagas selecionadas.")}}).catch(()=>{if(!cancelled)setStatus("Não foi possível consultar as vagas selecionadas.")}).finally(()=>{if(!cancelled)setPreviewLoading(false)});return()=>{cancelled=true}},[cutoffDate]);
 const toggle=(key:keyof Settings)=>(e:React.ChangeEvent<HTMLInputElement>)=>setS({...s,[key]:e.target.checked});
 async function save(){setStatus("Salvando…");const r=await fetch("/api/admin/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(s)});setStatus(r.ok?"Parâmetros salvos e ativos.":"Não foi possível salvar.")}
 async function clearJobs(){if(confirmation!==CONFIRMATION){setStatus(`Digite ${CONFIRMATION} para liberar a limpeza.`);return}if(!window.confirm(`Excluir ${jobs?.total??0} vagas do banco? Esta ação não pode ser desfeita.`))return;setCleaning(true);setStatus("Limpando base de vagas…");try{const response=await fetch("/api/admin/jobs",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({all:true,confirmation})}),data=await response.json();if(!response.ok)throw new Error(data.error);setJobs({total:0,active:0,closed:0});setConfirmation("");setStatus(`${data.deleted} vagas removidas. Usuários, perfil e integrações foram preservados.`)}catch(error){setStatus(error instanceof Error?error.message:"Não foi possível limpar a base.")}finally{setCleaning(false)}}
 async function clearJobsBefore(){const expected=`EXCLUIR VAGAS ANTERIORES A ${cutoffDate}`;if(cutoffConfirmation!==expected){setStatus(`Digite ${expected} para liberar a limpeza.`);return}if(!preview?.selected){setStatus("Não há vagas anteriores à data escolhida.");return}if(!window.confirm(`Excluir ${preview.selected} vagas recebidas antes de ${cutoffDate}? Esta ação não pode ser desfeita.`))return;setCleaningBefore(true);setStatus("Removendo vagas selecionadas…");try{const response=await fetch("/api/admin/jobs",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({before:cutoffDate,confirmation:cutoffConfirmation})}),data=await response.json();if(!response.ok)throw new Error(data.error);const summaryResponse=await fetch("/api/admin/jobs"),summary=await summaryResponse.json();if(summaryResponse.ok)setJobs(summary);setPreview({before:cutoffDate,selected:0});setCutoffConfirmation("");setStatus(`${data.deleted} vagas removidas. Usuários, perfil e integrações foram preservados.`)}catch(error){setStatus(error instanceof Error?error.message:"Não foi possível remover as vagas selecionadas.")}finally{setCleaningBefore(false)}}
 return <section className="admin-settings"><div className="admin-heading"><div><p className="eyebrow">ADMINISTRAÇÃO DO PORTAL</p><h3>Parâmetros operacionais</h3></div><span>Somente admin</span></div><div className="switch-grid">
 <label><input type="checkbox" checked={s.collectionEnabled} onChange={toggle("collectionEnabled")}/><span><b>Coleta automática</b><small>Autoriza a rotina diária das fontes.</small></span></label>
 <label><input type="checkbox" checked={s.emailImportEnabled} onChange={toggle("emailImportEnabled")}/><span><b>Importação por e-mail</b><small>Recebe alertas do conector Gmail.</small></span></label>
 <label><input type="checkbox" checked={s.enrichmentEnabled} onChange={toggle("enrichmentEnabled")}/><span><b>Enriquecimento oficial</b><small>Completa descrições por fontes monitoradas.</small></span></label>
 <label><input type="checkbox" checked={s.scheduledTriageEnabled} onChange={toggle("scheduledTriageEnabled")}/><span><b>Triagem agendada</b><small>Avalia por regras e IA ambígua sem intervenção manual.</small></span></label>
 <label><input type="checkbox" checked={s.scheduledTriageDraftQueueEnabled} onChange={toggle("scheduledTriageDraftQueueEnabled")}/><span><b>Preparar rascunho após aprovação</b><small>Enfileira automaticamente toda vaga aprovada com e-mail de contato válido.</small></span></label>
 <label><input type="checkbox" checked={s.scheduledTriageAutoCreateEnabled} onChange={toggle("scheduledTriageAutoCreateEnabled")} disabled={!s.scheduledTriageDraftQueueEnabled}/><span><b>Criar rascunho de verdade no Gmail</b><small>Só funciona com o item acima ligado; também controla o gatilho automático de 30 min. Desligado, a vaga fica enfileirada para ação manual.</small></span></label></div>
 <div className="profile-grid admin-number-grid"><label>Vagas por triagem agendada<input type="number" min="1" max="1000" value={s.scheduledTriageBatchSize} onChange={e=>setS({...s,scheduledTriageBatchSize:Number(e.target.value)})}/><small>De 1 a 1.000 vagas por rodada; padrão 100.</small></label><label>Janela inicial<select value={s.defaultPeriod} onChange={e=>setS({...s,defaultPeriod:e.target.value})}><option value="24">Últimas 24 horas</option><option value="72">Últimos 3 dias</option><option value="168">Últimos 7 dias</option><option value="all">Todas</option></select></label><label>Score padrão<input type="number" min="0" max="100" value={s.defaultMinScore} onChange={e=>setS({...s,defaultMinScore:Number(e.target.value)})}/></label><label>Vaga desatualizada após<input type="number" min="1" max="90" value={s.staleAfterDays} onChange={e=>setS({...s,staleAfterDays:Number(e.target.value)})}/></label><label>Retenção do histórico<input type="number" min="30" max="1095" value={s.retentionDays} onChange={e=>setS({...s,retentionDays:Number(e.target.value)})}/></label></div>
 {status&&<div className="notice">{status}</div>}<div className="source-actions"><button className="primary" onClick={save}>Salvar parâmetros</button></div>
 {isOwner&&<><section className="admin-danger-zone"><div><p className="eyebrow">MANUTENÇÃO DA BASE</p><h3>Excluir vagas por data de recebimento</h3><p>Remove somente vagas recebidas antes da data escolhida, incluindo itens do pipeline e alertas relacionados. {previewLoading?"Calculando a prévia…":preview?`${preview.selected} vaga(s) serão removidas.`:"Escolha uma data para consultar."}</p></div><a href="/api/admin/backup">↓ Baixar backup JSON</a><label>Excluir vagas recebidas antes de<input type="date" value={cutoffDate} onChange={event=>{setCutoffDate(event.target.value);setCutoffConfirmation("")}}/></label><label>Para confirmar, digite <strong>{`EXCLUIR VAGAS ANTERIORES A ${cutoffDate}`}</strong><input value={cutoffConfirmation} onChange={event=>setCutoffConfirmation(event.target.value)} placeholder={`EXCLUIR VAGAS ANTERIORES A ${cutoffDate}`}/></label><button type="button" className="admin-danger-button" disabled={cleaningBefore||previewLoading||!preview?.selected||cutoffConfirmation!==`EXCLUIR VAGAS ANTERIORES A ${cutoffDate}`} onClick={()=>void clearJobsBefore()}>{cleaningBefore?"Removendo…":"Excluir vagas selecionadas"}</button></section><section className="admin-danger-zone"><div><p className="eyebrow">MANUTENÇÃO DA BASE</p><h3>Limpar vagas importadas</h3><p>{jobs?`${jobs.total} vagas no banco (${jobs.active} ativas e ${jobs.closed} encerradas).`:"Consultando a base de vagas…"} A limpeza também remove itens do pipeline e alertas relacionados, mas preserva usuários, preferências, fontes e integrações.</p></div><a href="/api/admin/backup">↓ Baixar backup JSON</a><label>Para confirmar, digite <strong>{CONFIRMATION}</strong><input value={confirmation} onChange={event=>setConfirmation(event.target.value)} placeholder={CONFIRMATION}/></label><button type="button" className="admin-danger-button" disabled={cleaning||confirmation!==CONFIRMATION||!jobs?.total} onClick={()=>void clearJobs()}>{cleaning?"Limpando…":"Limpar base de vagas"}</button></section></>}</section>
}
