"use client";

import { useEffect,useState } from "react";

type Settings={collectionEnabled:boolean;emailImportEnabled:boolean;enrichmentEnabled:boolean;scheduledTriageEnabled:boolean;scheduledTriageBatchSize:number;queueDailyOperationBudget:number;manualQueueMessageSize:number;aiReviewChunkSize:number;defaultPeriod:string;defaultMinScore:number;staleAfterDays:number;retentionDays:number};
type JobSummary={total:number;active:number;closed:number;archivedEligibleForPurge:number};
const initial:Settings={collectionEnabled:true,emailImportEnabled:true,enrichmentEnabled:true,scheduledTriageEnabled:false,scheduledTriageBatchSize:100,queueDailyOperationBudget:7500,manualQueueMessageSize:25,aiReviewChunkSize:10,defaultPeriod:"24",defaultMinScore:70,staleAfterDays:7,retentionDays:180};
const CONFIRMATION="EXCLUIR TODAS AS VAGAS";
const DEFAULT_ARCHIVED_BEFORE="2026-08-15";
const confirmationForArchivedPurge=(date:string)=>`EXCLUIR VAGAS ARQUIVADAS ANTERIORES A ${date.split("-").reverse().join("/")}`;

export default function AdminSettings({isOwner}:{isOwner:boolean}){
 const[s,setS]=useState(initial),[status,setStatus]=useState("Carregando parâmetros…"),[jobs,setJobs]=useState<JobSummary|null>(null),[confirmation,setConfirmation]=useState(""),[archivedBefore,setArchivedBefore]=useState(DEFAULT_ARCHIVED_BEFORE),[archivedConfirmation,setArchivedConfirmation]=useState(""),[cleaning,setCleaning]=useState(false),[purgingArchived,setPurgingArchived]=useState(false);
 useEffect(()=>{let cancelled=false;Promise.all([fetch("/api/admin/settings"),fetch(`/api/admin/jobs?archivedBefore=${encodeURIComponent(archivedBefore)}`)]).then(async([settingsResponse,jobsResponse])=>({settingsResponse,jobsResponse,settings:await settingsResponse.json(),summary:await jobsResponse.json()})).then(({settingsResponse,jobsResponse,settings,summary})=>{if(cancelled)return;if(!settingsResponse.ok||!jobsResponse.ok)throw new Error();setS(settings.settings);setJobs(summary);setStatus("")}).catch(()=>{if(!cancelled)setStatus("Não foi possível carregar os parâmetros.")});return()=>{cancelled=true}},[archivedBefore]);
 const toggle=(key:keyof Settings)=>(e:React.ChangeEvent<HTMLInputElement>)=>setS({...s,[key]:e.target.checked});
 async function save(){setStatus("Salvando…");const r=await fetch("/api/admin/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(s)});setStatus(r.ok?"Parâmetros salvos e ativos.":"Não foi possível salvar.")}
 async function clearJobs(){if(confirmation!==CONFIRMATION){setStatus(`Digite ${CONFIRMATION} para liberar a limpeza.`);return}if(!window.confirm(`Excluir ${jobs?.total??0} vagas do banco? Esta ação não pode ser desfeita.`))return;setCleaning(true);setStatus("Limpando base de vagas…");try{const response=await fetch("/api/admin/jobs",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({all:true,confirmation})}),data=await response.json();if(!response.ok)throw new Error(data.error);setJobs({total:0,active:0,closed:0});setConfirmation("");setStatus(`${data.deleted} vagas removidas. Usuários, perfil e integrações foram preservados.`)}catch(error){setStatus(error instanceof Error?error.message:"Não foi possível limpar a base.")}finally{setCleaning(false)}}
 const archivedConfirmationText=confirmationForArchivedPurge(archivedBefore);
 async function purgeArchived(){if(archivedConfirmation!==archivedConfirmationText){setStatus(`Digite ${archivedConfirmationText} para liberar esta exclusão.`);return}const total=jobs?.archivedEligibleForPurge??0;if(!window.confirm(`Excluir definitivamente ${total} vagas arquivadas antes de ${archivedBefore.split("-").reverse().join("/")} e todos os dados vinculados? O backup deve estar guardado antes de continuar.`))return;setPurgingArchived(true);setStatus("Excluindo o recorte arquivado…");try{const response=await fetch("/api/admin/jobs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"purge_archived_before",archivedBefore,confirmation:archivedConfirmation})}),data=await response.json();if(!response.ok)throw new Error(data.error);setJobs(current=>current?{...current,total:current.total-data.deleted,closed:current.closed-data.deleted,archivedEligibleForPurge:0}:current);setArchivedConfirmation("");setStatus(`${data.deleted} vagas arquivadas e seus dados vinculados foram removidos definitivamente.`)}catch(error){setStatus(error instanceof Error?error.message:"Não foi possível excluir o recorte arquivado.")}finally{setPurgingArchived(false)}}
 return <section className="admin-settings"><div className="admin-heading"><div><p className="eyebrow">ADMINISTRAÇÃO DO PORTAL</p><h3>Parâmetros operacionais</h3></div><span>Somente admin</span></div><div className="switch-grid">
 <label><input type="checkbox" checked={s.collectionEnabled} onChange={toggle("collectionEnabled")}/><span><b>Coleta automática</b><small>Autoriza a rotina diária das fontes.</small></span></label>
 <label><input type="checkbox" checked={s.emailImportEnabled} onChange={toggle("emailImportEnabled")}/><span><b>Importação por e-mail</b><small>Recebe alertas do conector Gmail.</small></span></label>
 <label><input type="checkbox" checked={s.enrichmentEnabled} onChange={toggle("enrichmentEnabled")}/><span><b>Enriquecimento oficial</b><small>Completa descrições por fontes monitoradas.</small></span></label>
 <label><input type="checkbox" checked={s.scheduledTriageEnabled} onChange={toggle("scheduledTriageEnabled")}/><span><b>Triagem agendada</b><small>Avalia por regras e IA ambígua sem intervenção manual.</small></span></label>
 <div className="admin-fixed-policy"><b>Rascunhos imediatos</b><small>Toda vaga aprovada e elegível aciona a criação do rascunho no Gmail imediatamente. O Radar nunca envia o e-mail.</small></div></div>
 <div className="profile-grid admin-number-grid"><label>Vagas por triagem agendada<small>De 1 a 1.000 vagas por rodada; continua até concluir as vagas novas.</small><input type="number" min="1" max="1000" value={s.scheduledTriageBatchSize} onChange={e=>setS({...s,scheduledTriageBatchSize:Number(e.target.value)})}/></label><label>Janela inicial<select value={s.defaultPeriod} onChange={e=>setS({...s,defaultPeriod:e.target.value})}><option value="24">Últimas 24 horas</option><option value="72">Últimos 3 dias</option><option value="168">Últimos 7 dias</option><option value="all">Todas</option></select></label><label>Score padrão<input type="number" min="0" max="100" value={s.defaultMinScore} onChange={e=>setS({...s,defaultMinScore:Number(e.target.value)})}/></label><label>Vaga desatualizada após<input type="number" min="1" max="90" value={s.staleAfterDays} onChange={e=>setS({...s,staleAfterDays:Number(e.target.value)})}/></label><label>Retenção do histórico<input type="number" min="30" max="1095" value={s.retentionDays} onChange={e=>setS({...s,retentionDays:Number(e.target.value)})}/></label></div>
 <div className="profile-grid admin-number-grid"><label>Limite diário das filas<small>1.000–10.000 operações; 7.500 mantém margem no plano gratuito.</small><input type="number" min="1000" max="10000" value={s.queueDailyOperationBudget} onChange={e=>setS({...s,queueDailyOperationBudget:Number(e.target.value)})}/></label><label>Vagas por mensagem manual<small>1–100; mais vagas reduzem mensagens.</small><input type="number" min="1" max="100" value={s.manualQueueMessageSize} onChange={e=>setS({...s,manualQueueMessageSize:Number(e.target.value)})}/></label><label>Vagas por lote de IA<small>1–20; ajuste conforme as descrições.</small><input type="number" min="1" max="20" value={s.aiReviewChunkSize} onChange={e=>setS({...s,aiReviewChunkSize:Number(e.target.value)})}/></label></div>
 {status&&<div className="notice">{status}</div>}<div className="source-actions"><button className="primary" onClick={save}>Salvar parâmetros</button></div>
 {isOwner&&<section className="admin-danger-zone"><div><p className="eyebrow">MANUTENÇÃO DA BASE</p><h3>Limpar vagas importadas</h3><p>{jobs?`${jobs.total} vagas no banco (${jobs.active} ativas e ${jobs.closed} encerradas).`:"Consultando a base de vagas…"} A limpeza também remove itens do pipeline e alertas relacionados, mas preserva usuários, preferências, fontes e integrações.</p></div><a href="/api/admin/backup">↓ Baixar backup JSON</a><section><h4>Excluir somente o acervo arquivado antes da data escolhida</h4><label>Data limite<input type="date" value={archivedBefore} onChange={event=>{setArchivedBefore(event.target.value);setArchivedConfirmation("")}} required/></label><p>{jobs?`${jobs.archivedEligibleForPurge} vagas serão removidas junto com triagem, rascunhos registrados, pipeline, eventos e demais dados vinculados.`:"Consultando o recorte…"} Esta operação é atômica: se qualquer etapa falhar, nada é apagado.</p><label>Para confirmar, digite <strong>{archivedConfirmationText}</strong><input value={archivedConfirmation} onChange={event=>setArchivedConfirmation(event.target.value)} placeholder={archivedConfirmationText}/></label><button type="button" className="admin-danger-button" disabled={purgingArchived||!archivedBefore||archivedConfirmation!==archivedConfirmationText||!jobs?.archivedEligibleForPurge} onClick={()=>void purgeArchived()}>{purgingArchived?"Excluindo…":"Excluir recorte arquivado"}</button></section><label>Para confirmar, digite <strong>{CONFIRMATION}</strong><input value={confirmation} onChange={event=>setConfirmation(event.target.value)} placeholder={CONFIRMATION}/></label><button type="button" className="admin-danger-button" disabled={cleaning||confirmation!==CONFIRMATION||!jobs?.total} onClick={()=>void clearJobs()}>{cleaning?"Limpando…":"Limpar base de vagas"}</button></section>}</section>
}
