"use client";
import { useEffect,useState } from "react";
type Alert={id:string;title:string;company:string;url:string;score:number;reasons:string[];read:boolean;publishedAt:string};
export default function AlertCenter({close}:{close:()=>void}){
 const[alerts,setAlerts]=useState<Alert[]>([]),[unread,setUnread]=useState(0),[enabled,setEnabled]=useState(true),[minScore,setMinScore]=useState(80),[frequency,setFrequency]=useState("daily"),[message,setMessage]=useState("Carregando alertas…");
 async function load(){const r=await fetch("/api/alerts"),d=await r.json();if(r.ok){setAlerts(d.alerts);setUnread(d.unread);setEnabled(d.preferences.enabled);setMinScore(d.preferences.minScore);setFrequency(d.preferences.frequency);setMessage("")}else setMessage("Entre com sua conta para receber alertas personalizados.")}
 useEffect(()=>{fetch("/api/alerts").then(async r=>({ok:r.ok,data:await r.json()})).then(({ok,data:d})=>{if(ok){setAlerts(d.alerts);setUnread(d.unread);setEnabled(d.preferences.enabled);setMinScore(d.preferences.minScore);setFrequency(d.preferences.frequency);setMessage("")}else setMessage("Entre com sua conta para receber alertas personalizados.")})},[]);
 async function read(id:string){await fetch("/api/alerts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jobId:id})});setAlerts(a=>a.map(x=>x.id===id?{...x,read:true}:x));setUnread(n=>Math.max(0,n-1))}
 async function save(){const r=await fetch("/api/alerts",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({enabled,minScore,frequency})});setMessage(r.ok?"Preferências de alerta salvas.":"Não foi possível salvar.");if(r.ok)load()}
 return <div className="modal-backdrop" onClick={close}><section className="modal alerts-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><p className="eyebrow">VAGAS COMPATÍVEIS</p><div className="alerts-title"><div><h2>Meus alertas</h2><p>{unread} novas oportunidades ainda não visualizadas</p></div><span>{unread}</span></div><div className="alert-controls"><label><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Ativar alertas</label><label>Score mínimo <input type="number" min="0" max="100" value={minScore} onChange={e=>setMinScore(Number(e.target.value))}/></label><label>Resumo <select value={frequency} onChange={e=>setFrequency(e.target.value)}><option value="daily">Diário</option><option value="instant">Imediato no portal</option></select></label><button onClick={save}>Salvar</button></div>{message&&<div className="notice">{message}</div>}<div className="alert-list">{alerts.map(a=><article className={a.read?"read":""} key={a.id}><div><small>{a.company} · {a.score}% de aderência</small><h3>{a.title}</h3><p>{a.reasons.slice(0,2).join(" · ")}</p></div><button onClick={()=>{read(a.id);open(a.url,"_blank")}}>Ver vaga ↗</button></article>)}{!message&&alerts.length===0&&<div className="pipeline-empty">Nenhuma vaga atingiu seus critérios nos últimos 7 dias.</div>}</div></section></div>
}

