"use client";
import { useEffect,useMemo,useState } from "react";
import AdminSettings from "./AdminSettings";
import AlertCenter from "./AlertCenter";
import Analytics from "./Analytics";
import Monitoring from "./Monitoring";
import SourceList from "./SourceList";
import AuditTrail from "./AuditTrail";
import DataQuality from "./DataQuality";
import UserManagement from "./UserManagement";
type Job={id:string;score:number;title:string;company:string;location:string;mode:string;workMode?:string;age:string;publishedAt?:string;url?:string;description?:string;stack:string[];reasons:string[];stage:string};
type ApiJob={id:string;score?:number;title:string;company:string;location?:string;workMode?:string;publishedAt?:string;url?:string;description?:string;stack?:string[]};
type PipelineJob=ApiJob&{stage:string;note?:string};
type CurrentUser={displayName:string;email:string;fullName:string|null;role:"admin"|"user"};
type JobDetail={description:string;descriptionSource:string;stack?:string[]};
const demo:Job[]=[
{id:"demo-1",score:94,title:"Senior Cloud Security Engineer",company:"Nubank",location:"Brasil",mode:"Remoto",age:"2h",stack:["AWS","Terraform","Python"],reasons:["Stack aderente","Senioridade ideal","Remoto"],stage:"Nova"},
{id:"demo-2",score:89,title:"Security Operations Lead",company:"CloudWalk",location:"São Paulo",mode:"Híbrido",age:"4h",stack:["SIEM","SOC","Splunk"],reasons:["Área desejada","Liderança","Publicada hoje"],stage:"Nova"},
{id:"demo-3",score:84,title:"DevSecOps Engineer",company:"Stone",location:"Brasil",mode:"Remoto",age:"6h",stack:["Kubernetes","CI/CD","SAST"],reasons:["DevSecOps","Remoto","Boa aderência"],stage:"Salva"},
{id:"demo-4",score:78,title:"Cybersecurity Specialist",company:"Mercado Livre",location:"Osasco",mode:"Híbrido",age:"9h",stack:["IAM","Azure","GRC"],reasons:["Cybersecurity","Senior","Empresa-alvo"],stage:"Candidatura"}];
const nav=["Radar","Pipeline","Alertas","Métricas","Monitoramento","Auditoria","Qualidade","Usuários","Gmail RadarVagas","Fontes","Importações","Configurações"];
const adapt=(j:ApiJob):Job=>({id:j.id,score:j.score??70,title:j.title,company:j.company,location:j.location??"Não informado",mode:j.workMode??"Não informado",age:j.publishedAt?new Intl.RelativeTimeFormat("pt-BR",{numeric:"auto"}).format(-Math.max(1,Math.round((Date.now()-new Date(j.publishedAt).getTime())/36e5)),"hour"):"recente",stack:Array.isArray(j.stack)?j.stack:[],reasons:["Vaga ativa","Perfil compatível","Coletada pelo radar"],stage:"Nova",url:j.url,description:j.description});
export default function Dashboard(){
 const[active,setActive]=useState("Radar"),[query,setQuery]=useState(""),[items,setItems]=useState<Job[]>(demo),[selected,setSelected]=useState<Job>(demo[0]),[minScore,setMinScore]=useState(0),[period,setPeriod]=useState("24"),[mode,setMode]=useState("preview"),[importing,setImporting]=useState(false),[sourcesOpen,setSourcesOpen]=useState(false),[profileOpen,setProfileOpen]=useState(false),[pipelineOpen,setPipelineOpen]=useState(false),[pipelineItems,setPipelineItems]=useState<PipelineJob[]>([]),[pipelineLoading,setPipelineLoading]=useState(false),[profile,setProfile]=useState({seniority:"Senior",preferredMode:"Remoto",cities:"São Paulo, Brasil",masteredSkills:"AWS, Azure, SIEM, SOC, Terraform, Python",desiredAreas:"Cloud Security, Cybersecurity, DevSecOps, Security Operations",avoidTerms:"Estágio, Trainee",minScore:60}),[sourceName,setSourceName]=useState(""),[provider,setProvider]=useState("greenhouse"),[externalRef,setExternalRef]=useState(""),[json,setJson]=useState('[\n  {"company":"Empresa","title":"Security Engineer","url":"https://exemplo.com/vaga","workMode":"Remoto","stack":["AWS","SIEM"]}\n]'),[message,setMessage]=useState("");
 const[currentUser,setCurrentUser]=useState<CurrentUser|null>(null);
 const[gmailOpen,setGmailOpen]=useState(false);
 const[alertsOpen,setAlertsOpen]=useState(false);
 const[analyticsOpen,setAnalyticsOpen]=useState(false);
 const[monitorOpen,setMonitorOpen]=useState(false);
 const[auditOpen,setAuditOpen]=useState(false);
 const[qualityOpen,setQualityOpen]=useState(false);
 const[usersOpen,setUsersOpen]=useState(false);
 const[gmailSecret,setGmailSecret]=useState("");
 const[jobDetail,setJobDetail]=useState<JobDetail|null>(null);
 const[detailJob,setDetailJob]=useState<Job|null>(null);
 const[detailLoading,setDetailLoading]=useState(false);
 const[descriptionCopied,setDescriptionCopied]=useState(false);
 useEffect(()=>{fetch(`/api/jobs?limit=250&period=${period}`).then(r=>r.ok?r.json():Promise.reject()).then(data=>{const next=(data.jobs??[]).map(adapt);setItems(next);if(next.length)setSelected(next[0]);setMode("database")}).catch(()=>setMode("preview"))},[period]);
 useEffect(()=>{fetch("/api/profile").then(r=>r.ok?r.json():Promise.reject()).then(data=>setCurrentUser(data.user)).catch(()=>setCurrentUser(null))},[]);
 const filtered=useMemo(()=>items.filter(j=>j.score>=minScore&&`${j.title} ${j.company} ${j.stack.join(" ")}`.toLowerCase().includes(query.toLowerCase())),[items,query,minScore]);
 const selectedJob=filtered.find(job=>job.id===selected.id)??filtered[0]??null;
 function clearRadarFilters(){setQuery("");setMinScore(0);setPeriod("all")}
 async function runImport(){setMessage("Importando…");try{const csv=!json.trim().startsWith("[")&&!json.trim().startsWith("{"),response=await fetch("/api/admin/import",{method:"POST",headers:{"content-type":csv?"text/csv":"application/json"},body:json});const data=await response.json();if(!response.ok)throw new Error(data.error??"Falha na importação");setMessage(`${data.inserted} novas e ${data.updated} atualizadas.`);setTimeout(()=>location.reload(),900)}catch(e){setMessage(e instanceof Error?e.message:"Falha na importação")}}
 async function addSource(){setMessage("Salvando fonte…");const r=await fetch("/api/admin/sources",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:sourceName,provider,externalRef})}),data=await r.json();setMessage(r.ok?"Fonte cadastrada. Agora você pode coletar as vagas.":data.error??"Falha ao cadastrar")}
 async function collectNow(){setMessage("Coletando vagas nas fontes…");const r=await fetch("/api/admin/collect",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}),data=await r.json();if(r.ok){setMessage(`${data.received} encontradas: ${data.inserted} novas e ${data.updated} atualizadas.`);setTimeout(()=>location.reload(),1100)}else setMessage(data.error??"Falha na coleta")}
 async function openProfile(){setProfileOpen(true);const r=await fetch("/api/profile");if(r.ok){const d=await r.json(),p=d.profile;setProfile({seniority:p.seniority??"",preferredMode:p.preferredMode??"",cities:(p.cities??[]).join(", "),masteredSkills:(p.masteredSkills??[]).join(", "),desiredAreas:(p.desiredAreas??[]).join(", "),avoidTerms:(p.avoidTerms??[]).join(", "),minScore:p.minScore??60})}}
 async function saveProfile(){const list=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean),body={...profile,cities:list(profile.cities),masteredSkills:list(profile.masteredSkills),desiredAreas:list(profile.desiredAreas),avoidTerms:list(profile.avoidTerms)};const r=await fetch("/api/profile",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(body)});setMessage(r.ok?"Perfil salvo. Recalculando seu radar…":"Entre com sua conta para salvar o perfil.");if(r.ok)setTimeout(()=>location.reload(),900)}
 async function save(job:Job){if(job.id.startsWith("demo")){setMessage("Entre na versão publicada para salvar vagas reais.");return}const r=await fetch("/api/pipeline",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jobId:job.id,stage:"saved"})});setMessage(r.ok?"Vaga salva no seu pipeline.":"Entre com sua conta para salvar.")}
 async function openPipeline(){setPipelineOpen(true);setPipelineLoading(true);setMessage("");const r=await fetch("/api/pipeline");if(r.ok){const d=await r.json();setPipelineItems(d.items??[])}else setMessage("Entre com sua conta para acessar seu pipeline.");setPipelineLoading(false)}
 async function updatePipeline(jobId:string,stage:string,note:string){const r=await fetch("/api/pipeline",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jobId,stage,note})});if(r.ok){setPipelineItems(current=>current.map(item=>item.id===jobId?{...item,stage,note}:item));setMessage("Pipeline atualizado.")}else setMessage("Não foi possível atualizar o pipeline.")}
 async function configureGmail(){const r=await fetch("/api/admin/gmail-key",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({secret:gmailSecret})}),data=await r.json();setMessage(r.ok?"Chave exclusiva salva. Use a mesma chave no Google Apps Script.":data.error??"Falha ao salvar a chave")}
 async function loadJobDetail(job:Job){setDescriptionCopied(false);setJobDetail(null);if(job.id.startsWith("demo")){setDetailLoading(false);setJobDetail({description:job.description||"Descrição completa disponível nas oportunidades importadas.",descriptionSource:"preview"});return}setDetailLoading(true);try{const r=await fetch("/api/jobs/detail",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jobId:job.id})}),data=await r.json();if(!r.ok)throw new Error(data.error);setJobDetail(data);if(Array.isArray(data.stack)&&data.stack.length)setItems(current=>current.map(item=>item.id===job.id?{...item,stack:data.stack}:item))}catch{setJobDetail({description:job.description||"A descrição completa ainda não está disponível para esta vaga.",descriptionSource:"unavailable"})}finally{setDetailLoading(false)}}
 function openJobDetail(job:Job){setDescriptionCopied(false);setDetailJob(job);void loadJobDetail(job)}
 async function copyDescription(){const description=jobDetail?.description||detailJob?.description;if(!description)return;await navigator.clipboard.writeText(description);setDescriptionCopied(true);setTimeout(()=>setDescriptionCopied(false),1800)}
 const pipelineStages=[{id:"saved",label:"Salvas"},{id:"applied",label:"Candidaturas"},{id:"interview",label:"Entrevistas"},{id:"offer",label:"Ofertas"},{id:"rejected",label:"Encerradas"}];
 const userName=currentUser?.fullName||currentUser?.displayName||"Visitante",initials=userName.split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase();
 const isAdmin=currentUser?.role==="admin",visibleNav=nav.filter(item=>isAdmin||!new Set(["Monitoramento","Auditoria","Qualidade","Usuários","Gmail RadarVagas","Fontes","Importações"]).has(item)),icons:Record<string,string>={Radar:"⌁",Pipeline:"▦",Alertas:"●",Métricas:"▥",Monitoramento:"◌",Auditoria:"≡",Qualidade:"✓",Usuários:"♙","Gmail RadarVagas":"✉",Fontes:"◉",Importações:"↥",Configurações:"⚙"};
 return <main className="shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">R</span><span>RADAR<br/><b>CARREIRA</b></span></div><nav>{visibleNav.map(n=><button key={n} className={active===n?"active":""} onClick={()=>{setActive(n);if(n==="Pipeline")openPipeline();if(n==="Alertas")setAlertsOpen(true);if(n==="Métricas")setAnalyticsOpen(true);if(n==="Monitoramento")setMonitorOpen(true);if(n==="Auditoria")setAuditOpen(true);if(n==="Qualidade")setQualityOpen(true);if(n==="Usuários")setUsersOpen(true);if(n==="Gmail RadarVagas")setGmailOpen(true);if(n==="Importações")setImporting(true);if(n==="Fontes")setSourcesOpen(true);if(n==="Configurações")openProfile()}}><span>{icons[n]}</span>{n}{n==="Importações"&&<em>ADMIN</em>}</button>)}</nav><div className="sidebar-foot"><div className="avatar">{initials||"V"}</div><div><strong>{userName}</strong><small>{isAdmin?"Administrador":currentUser?"Usuário":"Não conectado"}</small></div>{currentUser&&<a className="signout" href="/signout-with-chatgpt?return_to=/">Sair</a>}</div></aside>
 <section className="content"><header><div><p className="eyebrow">RADAR · {period==="24"?"ÚLTIMAS 24 HORAS":period==="72"?"ÚLTIMOS 3 DIAS":period==="168"?"ÚLTIMOS 7 DIAS":"TODAS AS VAGAS"} · {mode==="database"?"BANCO ATIVO":"PRÉVIA LOCAL"}</p><h1>{active==="Radar"?`Seu radar de hoje${currentUser?`, ${userName.split(" ")[0]}`:""}`:active}</h1><p>Oportunidades ordenadas pela aderência ao seu perfil.</p></div><div className="header-actions">{!currentUser&&<a className="icon-btn" href="/signin-with-chatgpt?return_to=/">Entrar</a>}{isAdmin&&<a className="icon-btn" href={`/api/admin/report?period=${period}`}>↓ Relatório Excel</a>}{isAdmin&&<button className="primary" onClick={()=>setImporting(true)}>＋ Importar vagas</button>}</div></header>
 <div className="metrics"><article><span>VAGAS NO RADAR</span><strong>{items.length}</strong><small>Base disponível agora</small></article><article><span>ADERÊNCIA ALTA</span><strong>{items.filter(j=>j.score>=80).length}</strong><small>Score acima de 80</small></article><article><span>NO PIPELINE</span><strong>{items.filter(j=>j.stage!=="Nova").length}</strong><small>Estado individual</small></article><article className="accent"><span>MELHOR MATCH</span><strong>{items[0]?.score??0}%</strong><small>{items[0]?.company??"Aguardando vagas"}</small></article></div>
 {message&&<div className="notice">{message}</div>}<div className="toolbar"><div className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cargo, empresa ou tecnologia"/></div><select aria-label="Período das vagas" onChange={e=>setPeriod(e.target.value)} value={period}><option value="24">Últimas 24h</option><option value="72">Últimos 3 dias</option><option value="168">Últimos 7 dias</option><option value="all">Todas</option></select><div className="score-filter" role="group" aria-label="Score mínimo">{[{value:0,label:"Todos"},{value:70,label:"70+"},{value:80,label:"80+"}].map(option=><button type="button" key={option.value} aria-pressed={minScore===option.value} className={minScore===option.value?"active":""} onClick={()=>setMinScore(option.value)}>{option.label}</button>)}</div></div>
 <div className="workspace"><div className="job-list"><div className="list-head"><span>{filtered.length} oportunidades</span><span>mais recentes</span></div>{filtered.map(j=><button key={j.id} className={`job-card ${selectedJob?.id===j.id?"selected":""}`} onClick={()=>setSelected(j)}><div className="score">{j.score}<small>match</small></div><div className="job-main"><small>{j.company.toUpperCase()}</small><h3>{j.title}</h3><p>⌖ {j.location} · {j.mode} · {j.age}</p><div className="tags job-stack" aria-label="Tecnologias da vaga">{j.stack.length?j.stack.map(t=><span key={t}>{t}</span>):<span className="stack-unavailable">Stack não informada</span>}</div></div><span>♡</span></button>)}{filtered.length===0&&<div className="radar-empty"><strong>Nenhuma vaga corresponde aos filtros atuais.</strong><span>Reduza o score mínimo ou amplie o período para visualizar as oportunidades disponíveis.</span><button onClick={clearRadarFilters}>Mostrar todas as vagas</button></div>}</div>
 {selectedJob?<aside className="detail"><div className="detail-top"><span className="company-logo">{selectedJob.company[0]}</span><button onClick={()=>save(selectedJob)} aria-label="Salvar oportunidade">♡</button></div><small>{selectedJob.company.toUpperCase()}</small><h2>{selectedJob.title}</h2><p>⌖ {selectedJob.location} · {selectedJob.mode} · {selectedJob.age}</p><div className="match"><strong>{selectedJob.score}%</strong><span>aderência ao seu perfil</span><div className="bar"><i style={{width:`${selectedJob.score}%`}}/></div></div><h4>POR QUE É UM BOM MATCH</h4><ul>{selectedJob.reasons.map(r=><li key={r}>✓ {r}</li>)}</ul><h4>TECNOLOGIAS</h4><div className="tags">{selectedJob.stack.map(t=><span key={t}>{t}</span>)}</div><h4>RESUMO DA VAGA</h4><p className="summary">{selectedJob.description||"Abra a vaga no Radar para consultar a descrição completa e preparar sua mensagem de candidatura."}</p><div className="detail-actions radar-job-actions"><button onClick={()=>save(selectedJob)}>Salvar</button><button className="primary" onClick={()=>openJobDetail(selectedJob)}>Ver vaga no Radar</button><button className="linkedin-action" onClick={()=>selectedJob.url&&open(selectedJob.url,"_blank")}>LinkedIn ↗</button></div></aside>:<aside className="detail radar-detail-empty"><strong>Ajuste os filtros para selecionar uma oportunidade.</strong><span>Os detalhes aparecerão aqui assim que houver uma vaga visível.</span></aside>}</div></section>
 {detailJob&&<div className="modal-backdrop" onClick={()=>setDetailJob(null)}><section className="modal job-detail-modal" role="dialog" aria-modal="true" aria-label={`Detalhes da vaga ${detailJob.title}`} onClick={event=>event.stopPropagation()}><button className="modal-close" onClick={()=>setDetailJob(null)} aria-label="Fechar detalhes">×</button><div className="job-detail-heading"><div className="fit-badge"><strong>{detailJob.score}</strong><small>FIT</small></div><div><p className="eyebrow">ANÁLISE DE ADERÊNCIA</p><small>{detailJob.stack.slice(0,3).join(" · ")} · {detailJob.mode}</small></div></div><h2>{detailJob.title}</h2><p className="job-detail-meta">{detailJob.company} · {detailJob.location} ({detailJob.mode})</p><div className="job-detail-buttons"><button className="linkedin-action" onClick={()=>detailJob.url&&open(detailJob.url,"_blank")}>Abrir no LinkedIn ↗</button><button className="primary" onClick={()=>save(detailJob)}>Salvar oportunidade</button></div><section className="job-description"><div className="detail-section-title"><h4>DESCRIÇÃO DA VAGA</h4><div><span>{jobDetail?.descriptionSource==="linkedin"?"Fonte oficial":jobDetail?.descriptionSource==="stored"?"Descrição enriquecida":"Dados do alerta"}</span><button onClick={copyDescription} disabled={detailLoading||!(jobDetail?.description||detailJob.description)}>{descriptionCopied?"Copiada ✓":"Copiar descrição"}</button></div></div>{detailLoading?<p className="detail-loading">Buscando a descrição completa…</p>:<div className="description-scroll">{jobDetail?.description||detailJob.description||"A descrição completa ainda não está disponível para esta vaga."}</div>}<p className="external-use-hint">Copie a descrição para usar no ChatGPT ou em outra ferramenta externa.</p></section></section></div>}
 {usersOpen&&<UserManagement close={()=>setUsersOpen(false)}/>}
 {qualityOpen&&<DataQuality close={()=>setQualityOpen(false)}/>}
 {auditOpen&&<AuditTrail close={()=>setAuditOpen(false)}/>}
 {monitorOpen&&<Monitoring close={()=>setMonitorOpen(false)}/>}
 {analyticsOpen&&<Analytics close={()=>setAnalyticsOpen(false)}/>}
 {alertsOpen&&<AlertCenter close={()=>setAlertsOpen(false)}/>}
 {importing&&<div className="modal-backdrop" onClick={()=>setImporting(false)}><section className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setImporting(false)}>×</button><p className="eyebrow">PAINEL ADMINISTRATIVO</p><h2>Importar vagas</h2><p>Cole uma lista JSON ou o conteúdo de um CSV. Vagas repetidas são atualizadas automaticamente.</p><a className="csv-template" href="/modelo-importacao.csv" download>↓ Baixar modelo CSV</a><textarea value={json} onChange={e=>setJson(e.target.value)} spellCheck={false}/>{message&&<div className="notice">{message}</div>}<button className="primary" onClick={runImport}>Processar importação</button></section></div>}
 {sourcesOpen&&<div className="modal-backdrop" onClick={()=>setSourcesOpen(false)}><section className="modal source-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSourcesOpen(false)}>×</button><p className="eyebrow">COLETA AUTOMÁTICA</p><h2>Fontes de vagas</h2><p>Cadastre o identificador público da página de carreiras.</p><label>Empresa<input value={sourceName} onChange={e=>setSourceName(e.target.value)} placeholder="Ex.: Nubank"/></label><label>Plataforma<select value={provider} onChange={e=>setProvider(e.target.value)}><option value="greenhouse">Greenhouse</option><option value="lever">Lever</option><option value="ashby">Ashby</option></select></label><label>Identificador<input value={externalRef} onChange={e=>setExternalRef(e.target.value)} placeholder="Ex.: nubank"/></label><SourceList/>{message&&<div className="notice">{message}</div>}<div className="source-actions"><button onClick={addSource}>Cadastrar fonte</button><button className="primary" onClick={collectNow}>Coletar agora</button></div></section></div>}
 {pipelineOpen&&<div className="modal-backdrop" onClick={()=>setPipelineOpen(false)}><section className="modal pipeline-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setPipelineOpen(false)}>×</button><p className="eyebrow">ACOMPANHAMENTO DE CANDIDATURAS</p><h2>Meu pipeline</h2><p>Mova cada oportunidade entre as etapas e registre suas próximas ações.</p>{message&&<div className="notice">{message}</div>}{pipelineLoading?<div className="pipeline-empty">Carregando seu pipeline…</div>:<div className="kanban">{pipelineStages.map(stage=><section className="kanban-column" key={stage.id}><header><strong>{stage.label}</strong><span>{pipelineItems.filter(item=>item.stage===stage.id).length}</span></header>{pipelineItems.filter(item=>item.stage===stage.id).map(item=><article className="pipeline-card" key={item.id}><small>{item.company}</small><h3>{item.title}</h3><p>{item.location||"Local não informado"} · {item.workMode||"Modalidade não informada"}</p><select value={item.stage} onChange={e=>updatePipeline(item.id,e.target.value,item.note??"")}>{pipelineStages.map(option=><option value={option.id} key={option.id}>{option.label}</option>)}</select><textarea value={item.note??""} onChange={e=>setPipelineItems(current=>current.map(row=>row.id===item.id?{...row,note:e.target.value}:row))} placeholder="Anotações e próxima ação"/><div className="pipeline-actions"><button onClick={()=>updatePipeline(item.id,item.stage,item.note??"")}>Salvar nota</button><button onClick={()=>item.url&&open(item.url,"_blank")}>Abrir vaga ↗</button></div></article>)}</section>)}</div>}{!pipelineLoading&&pipelineItems.length===0&&<div className="pipeline-empty">Seu pipeline ainda está vazio. Salve uma vaga no Radar para começar.</div>}</section></div>}
 {profileOpen&&<div className="modal-backdrop" onClick={()=>setProfileOpen(false)}><section className="modal profile-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setProfileOpen(false)}>×</button><p className="eyebrow">MEU PERFIL</p><h2>Preferências do radar</h2><p>Separe listas por vírgulas. O score será recalculado ao salvar.</p><div className="profile-grid"><label>Senioridade<input value={profile.seniority} onChange={e=>setProfile({...profile,seniority:e.target.value})}/></label><label>Modalidade<select value={profile.preferredMode} onChange={e=>setProfile({...profile,preferredMode:e.target.value})}><option>Remoto</option><option>Híbrido</option><option>Presencial</option></select></label><label>Cidades<input value={profile.cities} onChange={e=>setProfile({...profile,cities:e.target.value})}/></label><label>Score mínimo<input type="number" min="0" max="100" value={profile.minScore} onChange={e=>setProfile({...profile,minScore:Number(e.target.value)})}/></label><label className="wide">Competências dominadas<input value={profile.masteredSkills} onChange={e=>setProfile({...profile,masteredSkills:e.target.value})}/></label><label className="wide">Áreas desejadas<input value={profile.desiredAreas} onChange={e=>setProfile({...profile,desiredAreas:e.target.value})}/></label><label className="wide">Termos a evitar<input value={profile.avoidTerms} onChange={e=>setProfile({...profile,avoidTerms:e.target.value})}/></label></div>{message&&<div className="notice">{message}</div>}<div className="source-actions"><button className="primary" onClick={saveProfile}>Salvar e recalcular</button></div>{isAdmin&&<AdminSettings/>}</section></div>}
 {gmailOpen&&<div className="modal-backdrop" onClick={()=>setGmailOpen(false)}><section className="modal gmail-modal" onClick={event=>event.stopPropagation()}><button className="modal-close" onClick={()=>setGmailOpen(false)}>×</button><p className="eyebrow">INTEGRAÇÃO ADMINISTRATIVA</p><h2>Gmail RadarVagas</h2><p>A ponte lê somente mensagens da etiqueta RadarVagas, envia alertas do LinkedIn ao banco e entrega seu resumo diário, sem armazenar sua senha.</p><div className="gmail-status"><span>1</span><div><strong>Crie uma chave exclusiva</strong><small>Use pelo menos 24 caracteres e guarde-a para configurar o Google.</small><input type="password" value={gmailSecret} onChange={event=>setGmailSecret(event.target.value)} placeholder="Chave exclusiva do Gmail"/></div><button onClick={configureGmail}>Salvar</button></div><div className="gmail-status"><span>2</span><div><strong>Baixe e autorize o conector</strong><small>Cole o arquivo em script.google.com e salve a mesma chave como RADAR_SECRET.</small></div><a href="/gmail-radarvagas.gs" download>Conector</a></div><div className="gmail-status"><span>3</span><div><strong>Ative a coleta e o resumo diário</strong><small>Execute importarRadarVagas para testar e instalarColetaDiaria uma vez para automatizar às 8h.</small></div></div>{message&&<div className="notice">{message}</div>}<div className="notice"><b>Integração completa:</b> alertas geram vagas, candidaturas atualizam o pipeline, fontes oficiais enriquecem descrições e as melhores oportunidades chegam por e-mail.</div></section></div>}
 </main>}
