"use client";
import { useEffect,useMemo,useState } from "react";
type Job={id:string;score:number;title:string;company:string;location:string;mode:string;workMode?:string;age:string;publishedAt?:string;url?:string;description?:string;stack:string[];reasons:string[];stage:string};
type ApiJob={id:string;score?:number;title:string;company:string;location?:string;workMode?:string;publishedAt?:string;url?:string;description?:string;stack?:string[]};
type PipelineJob=ApiJob&{stage:string;note?:string};
type CurrentUser={displayName:string;email:string;fullName:string|null;role:"admin"|"user"};
const demo:Job[]=[
{id:"demo-1",score:94,title:"Senior Cloud Security Engineer",company:"Nubank",location:"Brasil",mode:"Remoto",age:"2h",stack:["AWS","Terraform","Python"],reasons:["Stack aderente","Senioridade ideal","Remoto"],stage:"Nova"},
{id:"demo-2",score:89,title:"Security Operations Lead",company:"CloudWalk",location:"São Paulo",mode:"Híbrido",age:"4h",stack:["SIEM","SOC","Splunk"],reasons:["Área desejada","Liderança","Publicada hoje"],stage:"Nova"},
{id:"demo-3",score:84,title:"DevSecOps Engineer",company:"Stone",location:"Brasil",mode:"Remoto",age:"6h",stack:["Kubernetes","CI/CD","SAST"],reasons:["DevSecOps","Remoto","Boa aderência"],stage:"Salva"},
{id:"demo-4",score:78,title:"Cybersecurity Specialist",company:"Mercado Livre",location:"Osasco",mode:"Híbrido",age:"9h",stack:["IAM","Azure","GRC"],reasons:["Cybersecurity","Senior","Empresa-alvo"],stage:"Candidatura"}];
const nav=["Radar","Pipeline","Fontes","Importações","Configurações"];
const adapt=(j:ApiJob):Job=>({id:j.id,score:j.score??70,title:j.title,company:j.company,location:j.location??"Não informado",mode:j.workMode??"Não informado",age:j.publishedAt?new Intl.RelativeTimeFormat("pt-BR",{numeric:"auto"}).format(-Math.max(1,Math.round((Date.now()-new Date(j.publishedAt).getTime())/36e5)),"hour"):"recente",stack:Array.isArray(j.stack)?j.stack:[],reasons:["Vaga ativa","Perfil compatível","Coletada pelo radar"],stage:"Nova",url:j.url,description:j.description});
export default function Dashboard(){
 const[active,setActive]=useState("Radar"),[query,setQuery]=useState(""),[items,setItems]=useState<Job[]>(demo),[selected,setSelected]=useState<Job>(demo[0]),[minScore,setMinScore]=useState(70),[period,setPeriod]=useState("24"),[mode,setMode]=useState("preview"),[importing,setImporting]=useState(false),[sourcesOpen,setSourcesOpen]=useState(false),[profileOpen,setProfileOpen]=useState(false),[pipelineOpen,setPipelineOpen]=useState(false),[pipelineItems,setPipelineItems]=useState<PipelineJob[]>([]),[pipelineLoading,setPipelineLoading]=useState(false),[profile,setProfile]=useState({seniority:"Senior",preferredMode:"Remoto",cities:"São Paulo, Brasil",masteredSkills:"AWS, Azure, SIEM, SOC, Terraform, Python",desiredAreas:"Cloud Security, Cybersecurity, DevSecOps, Security Operations",avoidTerms:"Estágio, Trainee",minScore:60}),[sourceName,setSourceName]=useState(""),[provider,setProvider]=useState("greenhouse"),[externalRef,setExternalRef]=useState(""),[json,setJson]=useState('[\n  {"company":"Empresa","title":"Security Engineer","url":"https://exemplo.com/vaga","workMode":"Remoto","stack":["AWS","SIEM"]}\n]'),[message,setMessage]=useState("");
 const[currentUser,setCurrentUser]=useState<CurrentUser|null>(null);
 useEffect(()=>{fetch(`/api/jobs?limit=250&period=${period}`).then(r=>r.ok?r.json():Promise.reject()).then(data=>{const next=(data.jobs??[]).map(adapt);setItems(next);if(next.length)setSelected(next[0]);setMode("database")}).catch(()=>setMode("preview"))},[period]);
 useEffect(()=>{fetch("/api/profile").then(r=>r.ok?r.json():Promise.reject()).then(data=>setCurrentUser(data.user)).catch(()=>setCurrentUser(null))},[]);
 const filtered=useMemo(()=>items.filter(j=>j.score>=minScore&&`${j.title} ${j.company} ${j.stack.join(" ")}`.toLowerCase().includes(query.toLowerCase())),[items,query,minScore]);
 async function runImport(){setMessage("Importando…");try{const response=await fetch("/api/admin/import",{method:"POST",headers:{"content-type":"application/json"},body:json});const data=await response.json();if(!response.ok)throw new Error(data.error??"Falha na importação");setMessage(`${data.inserted} novas e ${data.updated} atualizadas.`);setTimeout(()=>location.reload(),900)}catch(e){setMessage(e instanceof Error?e.message:"Falha na importação")}}
 async function addSource(){setMessage("Salvando fonte…");const r=await fetch("/api/admin/sources",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:sourceName,provider,externalRef})}),data=await r.json();setMessage(r.ok?"Fonte cadastrada. Agora você pode coletar as vagas.":data.error??"Falha ao cadastrar")}
 async function collectNow(){setMessage("Coletando vagas nas fontes…");const r=await fetch("/api/admin/collect",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}),data=await r.json();if(r.ok){setMessage(`${data.received} encontradas: ${data.inserted} novas e ${data.updated} atualizadas.`);setTimeout(()=>location.reload(),1100)}else setMessage(data.error??"Falha na coleta")}
 async function openProfile(){setProfileOpen(true);const r=await fetch("/api/profile");if(r.ok){const d=await r.json(),p=d.profile;setProfile({seniority:p.seniority??"",preferredMode:p.preferredMode??"",cities:(p.cities??[]).join(", "),masteredSkills:(p.masteredSkills??[]).join(", "),desiredAreas:(p.desiredAreas??[]).join(", "),avoidTerms:(p.avoidTerms??[]).join(", "),minScore:p.minScore??60})}}
 async function saveProfile(){const list=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean),body={...profile,cities:list(profile.cities),masteredSkills:list(profile.masteredSkills),desiredAreas:list(profile.desiredAreas),avoidTerms:list(profile.avoidTerms)};const r=await fetch("/api/profile",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(body)});setMessage(r.ok?"Perfil salvo. Recalculando seu radar…":"Entre com sua conta para salvar o perfil.");if(r.ok)setTimeout(()=>location.reload(),900)}
 async function save(job:Job){if(job.id.startsWith("demo")){setMessage("Entre na versão publicada para salvar vagas reais.");return}const r=await fetch("/api/pipeline",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jobId:job.id,stage:"saved"})});setMessage(r.ok?"Vaga salva no seu pipeline.":"Entre com sua conta para salvar.")}
 async function openPipeline(){setPipelineOpen(true);setPipelineLoading(true);setMessage("");const r=await fetch("/api/pipeline");if(r.ok){const d=await r.json();setPipelineItems(d.items??[])}else setMessage("Entre com sua conta para acessar seu pipeline.");setPipelineLoading(false)}
 async function updatePipeline(jobId:string,stage:string,note:string){const r=await fetch("/api/pipeline",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jobId,stage,note})});if(r.ok){setPipelineItems(current=>current.map(item=>item.id===jobId?{...item,stage,note}:item));setMessage("Pipeline atualizado.")}else setMessage("Não foi possível atualizar o pipeline.")}
 const pipelineStages=[{id:"saved",label:"Salvas"},{id:"applied",label:"Candidaturas"},{id:"interview",label:"Entrevistas"},{id:"offer",label:"Ofertas"},{id:"rejected",label:"Encerradas"}];
 const userName=currentUser?.fullName||currentUser?.displayName||"Visitante",initials=userName.split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase();
 const isAdmin=currentUser?.role==="admin",visibleNav=nav.filter(item=>isAdmin||!new Set(["Fontes","Importações"]).has(item)),icons:Record<string,string>={Radar:"⌁",Pipeline:"▦",Fontes:"◉",Importações:"↥",Configurações:"⚙"};
 return <main className="shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">R</span><span>RADAR<br/><b>CARREIRA</b></span></div><nav>{visibleNav.map(n=><button key={n} className={active===n?"active":""} onClick={()=>{setActive(n);if(n==="Pipeline")openPipeline();if(n==="Importações")setImporting(true);if(n==="Fontes")setSourcesOpen(true);if(n==="Configurações")openProfile()}}><span>{icons[n]}</span>{n}{n==="Importações"&&<em>ADMIN</em>}</button>)}</nav><div className="sidebar-foot"><div className="avatar">{initials||"V"}</div><div><strong>{userName}</strong><small>{isAdmin?"Administrador":currentUser?"Usuário":"Não conectado"}</small></div>{currentUser&&<a className="signout" href="/signout-with-chatgpt?return_to=/">Sair</a>}</div></aside>
 <section className="content"><header><div><p className="eyebrow">RADAR · {period==="24"?"ÚLTIMAS 24 HORAS":period==="72"?"ÚLTIMOS 3 DIAS":period==="168"?"ÚLTIMOS 7 DIAS":"TODAS AS VAGAS"} · {mode==="database"?"BANCO ATIVO":"PRÉVIA LOCAL"}</p><h1>{active==="Radar"?`Seu radar de hoje${currentUser?`, ${userName.split(" ")[0]}`:""}`:active}</h1><p>Oportunidades ordenadas pela aderência ao seu perfil.</p></div><div className="header-actions">{!currentUser&&<a className="icon-btn" href="/signin-with-chatgpt?return_to=/">Entrar</a>}{isAdmin&&<a className="icon-btn" href={`/api/admin/report?period=${period}`}>↓ Relatório Excel</a>}{isAdmin&&<button className="primary" onClick={()=>setImporting(true)}>＋ Importar vagas</button>}</div></header>
 <div className="metrics"><article><span>VAGAS NO RADAR</span><strong>{items.length}</strong><small>Base disponível agora</small></article><article><span>ADERÊNCIA ALTA</span><strong>{items.filter(j=>j.score>=80).length}</strong><small>Score acima de 80</small></article><article><span>NO PIPELINE</span><strong>{items.filter(j=>j.stage!=="Nova").length}</strong><small>Estado individual</small></article><article className="accent"><span>MELHOR MATCH</span><strong>{items[0]?.score??0}%</strong><small>{items[0]?.company??"Aguardando vagas"}</small></article></div>
 {message&&<div className="notice">{message}</div>}<div className="toolbar"><div className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cargo, empresa ou tecnologia"/></div><select aria-label="Período das vagas" onChange={e=>setPeriod(e.target.value)} value={period}><option value="24">Últimas 24h</option><option value="72">Últimos 3 dias</option><option value="168">Últimos 7 dias</option><option value="all">Todas</option></select><select aria-label="Score mínimo" onChange={e=>setMinScore(Number(e.target.value))} value={minScore}><option value="0">Todos os scores</option><option value="70">Score 70+</option><option value="80">Score 80+</option></select></div>
 <div className="workspace"><div className="job-list"><div className="list-head"><span>{filtered.length} oportunidades</span><span>mais recentes</span></div>{filtered.map(j=><button key={j.id} className={`job-card ${selected.id===j.id?"selected":""}`} onClick={()=>setSelected(j)}><div className="score">{j.score}<small>match</small></div><div className="job-main"><small>{j.company.toUpperCase()}</small><h3>{j.title}</h3><p>⌖ {j.location} · {j.mode} · {j.age}</p><div className="tags">{j.stack.map(t=><span key={t}>{t}</span>)}</div></div><span>♡</span></button>)}</div>
 <aside className="detail"><div className="detail-top"><span className="company-logo">{selected.company[0]}</span><button onClick={()=>save(selected)}>♡</button></div><small>{selected.company.toUpperCase()}</small><h2>{selected.title}</h2><p>⌖ {selected.location} · {selected.mode} · {selected.age}</p><div className="match"><strong>{selected.score}%</strong><span>aderência ao seu perfil</span><div className="bar"><i style={{width:`${selected.score}%`}}/></div></div><h4>POR QUE É UM BOM MATCH</h4><ul>{selected.reasons.map(r=><li key={r}>✓ {r}</li>)}</ul><h4>TECNOLOGIAS</h4><div className="tags">{selected.stack.map(t=><span key={t}>{t}</span>)}</div><h4>RESUMO DA VAGA</h4><p className="summary">{selected.description||"Descrição detalhada disponível após a importação da oportunidade."}</p><div className="detail-actions"><button onClick={()=>save(selected)}>Salvar</button><button className="primary" onClick={()=>selected.url&&open(selected.url,"_blank")}>Ver vaga ↗</button></div></aside></div></section>
 {importing&&<div className="modal-backdrop" onClick={()=>setImporting(false)}><section className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setImporting(false)}>×</button><p className="eyebrow">PAINEL ADMINISTRATIVO</p><h2>Importar vagas</h2><p>Cole uma lista JSON. Vagas repetidas são atualizadas automaticamente.</p><textarea value={json} onChange={e=>setJson(e.target.value)} spellCheck={false}/>{message&&<div className="notice">{message}</div>}<button className="primary" onClick={runImport}>Processar importação</button></section></div>}
 {sourcesOpen&&<div className="modal-backdrop" onClick={()=>setSourcesOpen(false)}><section className="modal source-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSourcesOpen(false)}>×</button><p className="eyebrow">COLETA AUTOMÁTICA</p><h2>Fontes de vagas</h2><p>Cadastre o identificador público da página de carreiras.</p><label>Empresa<input value={sourceName} onChange={e=>setSourceName(e.target.value)} placeholder="Ex.: Nubank"/></label><label>Plataforma<select value={provider} onChange={e=>setProvider(e.target.value)}><option value="greenhouse">Greenhouse</option><option value="lever">Lever</option><option value="ashby">Ashby</option></select></label><label>Identificador<input value={externalRef} onChange={e=>setExternalRef(e.target.value)} placeholder="Ex.: nubank"/></label>{message&&<div className="notice">{message}</div>}<div className="source-actions"><button onClick={addSource}>Cadastrar fonte</button><button className="primary" onClick={collectNow}>Coletar agora</button></div></section></div>}
 {pipelineOpen&&<div className="modal-backdrop" onClick={()=>setPipelineOpen(false)}><section className="modal pipeline-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setPipelineOpen(false)}>×</button><p className="eyebrow">ACOMPANHAMENTO DE CANDIDATURAS</p><h2>Meu pipeline</h2><p>Mova cada oportunidade entre as etapas e registre suas próximas ações.</p>{message&&<div className="notice">{message}</div>}{pipelineLoading?<div className="pipeline-empty">Carregando seu pipeline…</div>:<div className="kanban">{pipelineStages.map(stage=><section className="kanban-column" key={stage.id}><header><strong>{stage.label}</strong><span>{pipelineItems.filter(item=>item.stage===stage.id).length}</span></header>{pipelineItems.filter(item=>item.stage===stage.id).map(item=><article className="pipeline-card" key={item.id}><small>{item.company}</small><h3>{item.title}</h3><p>{item.location||"Local não informado"} · {item.workMode||"Modalidade não informada"}</p><select value={item.stage} onChange={e=>updatePipeline(item.id,e.target.value,item.note??"")}>{pipelineStages.map(option=><option value={option.id} key={option.id}>{option.label}</option>)}</select><textarea value={item.note??""} onChange={e=>setPipelineItems(current=>current.map(row=>row.id===item.id?{...row,note:e.target.value}:row))} placeholder="Anotações e próxima ação"/><div className="pipeline-actions"><button onClick={()=>updatePipeline(item.id,item.stage,item.note??"")}>Salvar nota</button><button onClick={()=>item.url&&open(item.url,"_blank")}>Abrir vaga ↗</button></div></article>)}</section>)}</div>}{!pipelineLoading&&pipelineItems.length===0&&<div className="pipeline-empty">Seu pipeline ainda está vazio. Salve uma vaga no Radar para começar.</div>}</section></div>}
 {profileOpen&&<div className="modal-backdrop" onClick={()=>setProfileOpen(false)}><section className="modal profile-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setProfileOpen(false)}>×</button><p className="eyebrow">MEU PERFIL</p><h2>Preferências do radar</h2><p>Separe listas por vírgulas. O score será recalculado ao salvar.</p><div className="profile-grid"><label>Senioridade<input value={profile.seniority} onChange={e=>setProfile({...profile,seniority:e.target.value})}/></label><label>Modalidade<select value={profile.preferredMode} onChange={e=>setProfile({...profile,preferredMode:e.target.value})}><option>Remoto</option><option>Híbrido</option><option>Presencial</option></select></label><label>Cidades<input value={profile.cities} onChange={e=>setProfile({...profile,cities:e.target.value})}/></label><label>Score mínimo<input type="number" min="0" max="100" value={profile.minScore} onChange={e=>setProfile({...profile,minScore:Number(e.target.value)})}/></label><label className="wide">Competências dominadas<input value={profile.masteredSkills} onChange={e=>setProfile({...profile,masteredSkills:e.target.value})}/></label><label className="wide">Áreas desejadas<input value={profile.desiredAreas} onChange={e=>setProfile({...profile,desiredAreas:e.target.value})}/></label><label className="wide">Termos a evitar<input value={profile.avoidTerms} onChange={e=>setProfile({...profile,avoidTerms:e.target.value})}/></label></div>{message&&<div className="notice">{message}</div>}<div className="source-actions"><button className="primary" onClick={saveProfile}>Salvar e recalcular</button></div></section></div>}
 </main>}
