"use client";
import { useEffect,useState } from "react";

export default function LinkedInExtensionSetup({close}:{close:()=>void}){
 const[key,setKey]=useState(""),[configured,setConfigured]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/admin/linkedin-key").then(async response=>{if(!response.ok)throw new Error();const data=await response.json();setConfigured(Boolean(data.configured))}).catch(()=>setMessage("Não foi possível consultar a configuração."))},[]);
 function generate(){const bytes=crypto.getRandomValues(new Uint8Array(24));setKey(Array.from(bytes,byte=>byte.toString(16).padStart(2,"0")).join(""));setMessage("Chave criada. Copie-a antes de fechar esta janela.")}
 async function copy(){if(!key)return;await navigator.clipboard.writeText(key);setMessage("Chave copiada. Agora cole-a no painel da extensão.")}
 async function save(){const response=await fetch("/api/admin/linkedin-key",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({secret:key})}),data=await response.json();if(!response.ok){setMessage(data.error??"Não foi possível salvar a chave.");return}setConfigured(true);setMessage("Chave salva e conexão liberada. Copie a mesma chave para a extensão.")}
 return <div className="modal-backdrop" onClick={close}><section className="modal gmail-modal linkedin-setup" role="dialog" aria-modal="true" aria-label="Conectar extensão LinkedIn" onClick={event=>event.stopPropagation()}><button className="modal-close" onClick={close}>×</button><p className="eyebrow">INTEGRAÇÃO ADMINISTRATIVA</p><h2>Extensão LinkedIn</h2><p>Crie uma chave exclusiva para autorizar o envio automático de vagas ao banco do Radar.</p><div className="integration-state"><i className={configured?"on":"off"}/><strong>{configured?"Conexão já configurada":"Conexão ainda não configurada"}</strong></div><div className="gmail-status"><span>1</span><div><strong>Gere uma chave segura</strong><small>A chave aparece apenas agora. Ela não é sua senha do LinkedIn.</small><input type="text" readOnly value={key} placeholder="Clique em Gerar chave"/></div><button onClick={generate}>Gerar chave</button></div><div className="gmail-status"><span>2</span><div><strong>Salve e copie a chave</strong><small>O Radar guarda somente uma impressão protegida, não o texto da chave.</small></div><div className="setup-buttons"><button onClick={save} disabled={!key}>Salvar</button><button onClick={copy} disabled={!key}>Copiar</button></div></div><div className="gmail-status"><span>3</span><div><strong>Cole na extensão</strong><small>Abra a extensão, ative Enviar ao Radar, cole em Chave exclusiva do coletor e clique em Testar conexão.</small></div></div>{message&&<div className="notice">{message}</div>}</section></div>
}
