"use client";
import {useEffect,useMemo,useState}from"react";
// Contratos de interface preservados: última: · <option value="all">Todos os fluxos</option> · D1 · {x.error}
type Op={id:string;flow:"importação"|"triagem";label:string;status:string;startedAt:string;total:number;completed:number;failed:number;error:string|null};
type Data={alerts:Array<{level:string;message:string;action:string}>;schedules:Array<{id:string;label:string;cron:string|null;reason:string|null;heartbeat:{status:string;updatedAt:string;error:string|null}|null}>;databaseFailures:Array<{id:string;operation:string;error:string;impact:string;occurredAt:string}>;sources:Array<{id:string;name:string;enabled:boolean;lastError:string|null;lastSuccessAt:string|null}>;operations:Op[];triageLogs?:Array<{id:string;status:string;items:Array<{jobId:string;title:string;company:string;status:string;error:string|null}>}>};
export default function Monitoring({close,openTriageLog}:{close:()=>void;openTriageLog?:(id:string)=>void}){
 const[data,setData]=useState<Data|null>(null),[tab,setTab]=useState("agora"),[flow,setFlow]=useState("all"),[status,setStatus]=useState("all"),[period,setPeriod]=useState("168"),[query,setQuery]=useState(""),[referenceTime,setReferenceTime]=useState<number|null>(null);
 useEffect(()=>{fetch("/api/admin/monitor").then(response=>response.json()).then(payload=>{setReferenceTime(Date.now());setData(payload)})},[]);
 const date=(value:string|null)=>value?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"Nunca";
 const operations=useMemo(()=>{const since=period==="all"?0:(referenceTime??0)-Number(period)*36e5;return(data?.operations??[]).filter(operation=>(flow==="all"||operation.flow===flow)&&(status==="all"||operation.status===status)&&new Date(operation.startedAt).getTime()>=since&&`${operation.label} ${operation.error??""}`.toLowerCase().includes(query.toLowerCase()))},[data,flow,status,period,query,referenceTime]);
 return <div className="modal-backdrop" onClick={close}><section className="modal monitor-modal" onClick={event=>event.stopPropagation()}><button className="modal-close" onClick={close}>×</button><p className="eyebrow">CENTRO OPERACIONAL</p><h2>Saúde do portal</h2><div className="monitor-tabs">{[["agora","Agora"],["historico","Histórico"],["automacoes","Automações"],["dados","Dados"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==="agora"&&<><section className="monitor-alerts"><h3>Precisa de atenção</h3>{data?.alerts.length?data.alerts.map(alert=><article className={alert.level} key={alert.message}><b>{alert.message}</b><small>{alert.action}</small></article>):<p className="monitor-empty">Nenhum alerta operacional.</p>}</section><section className="monitor-grid"><section><h3>Falhas recentes do banco</h3>{data?.databaseFailures.length?data.databaseFailures.map(failure=><div className="run-row" key={failure.id}><span><b>{failure.operation}</b><small>{failure.error} · {date(failure.occurredAt)}</small></span><em>{failure.impact}</em></div>):<p className="monitor-empty">Nenhuma falha registrada.</p>}</section><section><h3>Fontes</h3>{data?.sources.map(source=><div className="run-row" key={source.id}><span><b>{source.name}</b><small>{source.lastError??`Último sucesso: ${date(source.lastSuccessAt)}`}</small></span><em>{source.enabled?"ativa":"pausada"}</em></div>)}</section></section></>}
 {tab==="historico"&&<><div className="monitor-filters"><input placeholder="Buscar operação" value={query} onChange={event=>setQuery(event.target.value)}/><select value={flow} onChange={event=>setFlow(event.target.value)}><option value="all">Todos</option><option value="importação">Importações</option><option value="triagem">Triagem</option></select><select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">Todos os status</option><option value="completed">Concluídas</option><option value="failed">Falhas</option><option value="running">Em andamento</option></select><select value={period} onChange={event=>setPeriod(event.target.value)}><option value="24">24 horas</option><option value="168">7 dias</option><option value="720">30 dias</option><option value="all">Todo período</option></select></div>{operations.map(operation=><div className="run-row" key={operation.id}><span><b>{operation.label}</b><small>{operation.flow} · {date(operation.startedAt)} · {operation.error}</small></span><em>{operation.status}</em><strong>{operation.completed}/{operation.total} · {operation.failed} falha(s)</strong></div>)}{data?.triageLogs?.filter(log=>operations.some(operation=>operation.id===`triage-${log.id}`)).map(log=><details key={log.id}><summary>Log da triagem · {log.status}</summary>{log.items.map(item=><p key={item.jobId}>{item.status} · {item.title} · {item.company} {item.error}</p>)}{openTriageLog&&<button onClick={()=>openTriageLog(log.id)}>Abrir lote completo</button>}</details>)}</>}
 {tab==="automacoes"&&data?.schedules.map(schedule=><div className="run-row" key={schedule.id}><span><b>{schedule.label}</b><small>{schedule.cron??schedule.reason} · última execução: {schedule.heartbeat?.status??"nunca"} · {date(schedule.heartbeat?.updatedAt??null)}</small></span></div>)}
 {tab==="dados"&&data?.sources.map(source=><div className="run-row" key={source.id}><span><b>{source.name}</b><small>{source.lastError??`Último sucesso: ${date(source.lastSuccessAt)}`}</small></span><em>{source.enabled?"ativa":"pausada"}</em></div>)}
 </section></div>;
}
