import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { getDb } from "../../../../db/index";
import { platformSettings } from "../../../../db/schema";
import { getChatGPTUser } from "../../../chatgpt-auth";
import { can } from "../../../../lib/rbac";
export const dynamic="force-dynamic";
const defaults={id:"global",collectionEnabled:true,emailImportEnabled:true,enrichmentEnabled:true,scheduledTriageEnabled:false,scheduledTriageDraftQueueEnabled:false,scheduledTriageAutoCreateEnabled:false,defaultPeriod:"24",defaultMinScore:70,staleAfterDays:7,retentionDays:180,updatedBy:null,updatedAt:new Date()};
async function admin(permissionId:"settings.view"|"settings.edit"){const u=await getChatGPTUser();if(!u)return null;return await can(u,permissionId)?u:null}
export async function GET(){if(!await admin("settings.view"))return NextResponse.json({error:"Acesso de administrador necessário"},{status:403});const db=getDb();let settings=(await db.select().from(platformSettings).where(eq(platformSettings.id,"global")).limit(1))[0];if(!settings){await db.insert(platformSettings).values(defaults);settings=defaults}return NextResponse.json({settings})}
export async function PUT(request:Request){const u=await admin("settings.edit");if(!u)return NextResponse.json({error:"Acesso de administrador necessário"},{status:403});const b=await request.json() as Record<string,unknown>,period=String(b.defaultPeriod??"24");const values={id:"global",collectionEnabled:Boolean(b.collectionEnabled),emailImportEnabled:Boolean(b.emailImportEnabled),enrichmentEnabled:Boolean(b.enrichmentEnabled),scheduledTriageEnabled:Boolean(b.scheduledTriageEnabled),scheduledTriageDraftQueueEnabled:Boolean(b.scheduledTriageDraftQueueEnabled),scheduledTriageAutoCreateEnabled:Boolean(b.scheduledTriageAutoCreateEnabled),defaultPeriod:new Set(["24","72","168","all"]).has(period)?period:"24",defaultMinScore:Math.max(0,Math.min(100,Number(b.defaultMinScore)||0)),staleAfterDays:Math.max(1,Math.min(90,Number(b.staleAfterDays)||7)),retentionDays:Math.max(30,Math.min(1095,Number(b.retentionDays)||180)),updatedBy:u.userId,updatedAt:new Date()};await getDb().insert(platformSettings).values(values).onConflictDoUpdate({target:platformSettings.id,set:values});return NextResponse.json({ok:true,settings:values})}
